#!/bin/bash
set -Eeuxo pipefail

VERSION=7.0.11
BUILD=260821
ARCHIVE="limesurvey${VERSION}+${BUILD}.zip"
URL="https://download.limesurvey.org/latest-master/$ARCHIVE"
SHA256=cef826be3e32ae5dd443b1d8f222fc9f3214688115705271c114d4492d7ca9ab

proxy=()
if [[ -n ${FAB_HTTP_PROXY:-} ]]; then
    proxy=(--proxy "$FAB_HTTP_PROXY")
fi

curl --fail --location "${proxy[@]}" "$URL" \
    --output "/usr/local/src/$ARCHIVE"
printf '%s  %s\n' "$SHA256" "/usr/local/src/$ARCHIVE" |
    sha256sum --check -
