#!/bin/sh -ex

DB_NAME=limesurvey
DB_USER=limesurvey
DB_PASS=$(mcookie)

ADMIN_NAME=admin
ADMIN_PASS=turnkey
ADMIN_MAIL=admin@example.com

SRC=/usr/local/src
WEBROOT=/var/www/limesurvey

# unpack and set required permissions
tar -zxf $SRC/limesurvey*.tar.gz -C $(dirname $WEBROOT)
rm $SRC/limesurvey*

chown -R root:root $WEBROOT
chown -R www-data:www-data $WEBROOT/tmp
chown -R www-data:www-data $WEBROOT/upload
chown -R www-data:www-data $WEBROOT/application/config

# configure apache
a2dissite 000-default
a2ensite limesurvey
a2enmod rewrite

# Increase PHP memory for Limesurvey minimal requirements i.e. 64 MB
sed -i s/memory_limit\ =\ 32M/memory_limit\ =\ 64M/  /etc/php/7.0/apache2/php.ini 

# start services
service apache2 start
service mysql start

# convenience execution variables
MYSQL_BATCH="mysql --user=root --password=$MYSQL_PASS --batch"
MYSQL_ADMIN="mysqladmin --user=root --password=$MYSQL_PASS"

$MYSQL_ADMIN create $DB_NAME
$MYSQL_BATCH --execute "grant all privileges on $DB_NAME.* to $DB_USER@localhost identified by '$DB_PASS'; flush privileges;"

# curl based installation
URL="http://127.0.0.1/index.php"
CURL="curl -c /tmp/cookie -b /tmp/cookie"
EMAIL=$(echo $ADMIN_MAIL | sed s/@/%40/)

$CURL "${URL}?r=installer"
$CURL "${URL}?r=installer/welcome"

YII_CSRF=$( awk '/YII_CSRF_TOKEN/{print $7}' /tmp/cookie )

$CURL "$URL?r=installer/welcome"  --data "YII_CSRF_TOKEN=$YII_CSRF&installerLang=en"
$CURL "${URL}?r=installer/license" --data "YII_CSRF_TOKEN=$YII_CSRF"
$CURL "${URL}?r=installer/precheck"
$CURL "${URL}?r=installer/database"
$CURL "${URL}?r=installer/database" --data "YII_CSRF_TOKEN=$YII_CSRF&InstallerConfigForm%5Bdbtype%5D=mysql&InstallerConfigForm%5Bdblocation%5D=localhost&InstallerConfigForm%5Bdbuser%5D=$DB_USER&InstallerConfigForm%5Bdbpwd%5D=$DB_PASS&InstallerConfigForm%5Bdbname%5D=$DB_NAME&InstallerConfigForm%5Bdbprefix%5D=&yt0=Next"

$CURL "${URL}?r=installer/populatedb" --data "YII_CSRF_TOKEN=$YII_CSRF&createdbstep2=Populate+database"
$CURL "${URL}?r=installer/optional"
$CURL "${URL}?r=/installer/optional" --data "YII_CSRF_TOKEN=$YII_CSRF&InstallerConfigForm%5BadminLoginName%5D=$ADMIN_NAME&InstallerConfigForm%5BadminLoginPwd%5D=$ADMIN_PASS&InstallerConfigForm%5BconfirmPwd%5D=$ADMIN_PASS&InstallerConfigForm%5BadminName%5D=Administrator&InstallerConfigForm%5BadminEmail%5D=$EMAIL&InstallerConfigForm%5BsiteName%5D=TurnKey+LimeSurvey&InstallerConfigForm%5Bsurveylang%5D=en"
$CURL "${URL}?r=/admin"

# stop services
service apache2 stop
service mysql stop
