#!/bin/bash
set -Eeuxo pipefail

VERSION=7.0.11
BUILD=260821

DB_NAME=limesurvey
DB_USER=limesurvey
DB_PASS=$(mcookie)

ADMIN_NAME=admin
ADMIN_PASS=turnkey-build-password
ADMIN_MAIL=admin@example.com

SRC=/usr/local/src
WEBROOT=/var/www/limesurvey
ARCHIVE="$SRC/limesurvey${VERSION}+${BUILD}.zip"
CONF="$WEBROOT/application/config/config.php"

unzip -q "$ARCHIVE" -d "$(dirname "$WEBROOT")"
rm "$ARCHIVE"
test "$(php -r '$config=[]; include $argv[1]; echo $config["versionnumber"];' \
    "$WEBROOT/application/config/version.php")" = "$VERSION"

cp "$WEBROOT/application/config/config-sample-mysql.php" "$CONF"
sed -i \
    -e 's/host=127.0.0.1/host=localhost/' \
    -e "s/'username' => 'root'/'username' => '$DB_USER'/" \
    -e "s/'password' => 'root'/'password' => '$DB_PASS'/" \
    "$CONF"
sed -i "/'debug' => 0/i\\        'force_ssl' => 'on'," "$CONF"

chown -R root:root "$WEBROOT"
chown -R www-data:www-data \
    "$WEBROOT/application/config" "$WEBROOT/tmp" "$WEBROOT/upload"

a2dissite 000-default
a2enmod headers rewrite
a2ensite limesurvey

service mariadb start
mariadb --batch --execute "CREATE DATABASE $DB_NAME CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci; CREATE USER '$DB_USER'@'localhost' IDENTIFIED BY '$DB_PASS'; GRANT ALL PRIVILEGES ON $DB_NAME.* TO '$DB_USER'@'localhost'; FLUSH PRIVILEGES;"

(
    cd "$WEBROOT"
    runuser -u www-data -- php application/commands/console.php \
        install "$ADMIN_NAME" "$ADMIN_PASS" Administrator "$ADMIN_MAIL" verbose
)

test "$(mariadb --batch --skip-column-names "$DB_NAME" \
    --execute 'SELECT COUNT(*) FROM lime_users')" = 1
find "$WEBROOT/application/config" -maxdepth 1 -name allowed_hosts.php -delete

service mariadb stop
