#!/bin/bash -e
# regenerate limesurvey secrets and mysql password

. /etc/default/inithooks

CONF=/var/www/limesurvey/application/config/config.php
PASSWORD=$(mcookie)
sed -i "s|password' =>.*|password' => '$PASSWORD',|" $CONF
$INITHOOKS_PATH/bin/mysqlconf.py --user=limesurvey --pass="$PASSWORD"

